[project]
name = "websocket-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "redis[hiredis]>=5.2.1",
    "uvicorn>=0.34.0",
    "websockets>=15.0.1",
]
